### ISSUE TITLE
No command "N4BiasFieldCorrection" found on host kim-X10DAi. Please check that the corresponding package is installed.

### ISSUE THREAD

**Issue by wky1998** [quqixun/BrainPrep#1]
Thanks for your work，but an error occurred when I run bias_correction

No command "N4BiasFieldCorrection" found on host kim-X10DAi. Please check that the corresponding package is installed.

**Comment by quqixun** [comment]
> Thanks for your work，but an error occurred when I run bias_correction
> 
> No command "N4BiasFieldCorrection" found on host kim-X10DAi. Please check that the corresponding package is installed.

[N4BiasFieldCorrection](https://github.com/ANTsX/ANTs/blob/master/Examples/N4BiasFieldCorrection.cxx) is a command from ANTs.
Please check if ANTs was installed correctly.

If so, use the following command to check if N4BiasFieldCorrection could be called.
It should return the path of the binary executable file of N4BiasFieldCorrection.
[See here.](https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS#set-path-and-antspath)
```
which N4BiasFieldCorrection
```
Good luck!

**Comment by wky1998** [comment]
thanks, i just installed ANTs，i also can run which N4BiasFieldCorrection and antsRegistrationSyN.sh
but i don't understand why it still error 
No command "N4BiasFieldCorrection" found on host kim-X10DAi. Please check that the corresponding package is installed.

**Comment by quqixun** [comment]
> thanks, i just installed ANTs，i also can run which N4BiasFieldCorrection and antsRegistrationSyN.sh
> but i don't understand why it still error
> No command "N4BiasFieldCorrection" found on host kim-X10DAi. Please check that the corresponding package is installed.

In my code, N4BiasFieldCorrection is called by nipype's interface for ANTs, [See here.](https://github.com/nipy/nipype/blob/master/nipype/interfaces/ants/segmentation.py#L316)  
You can find the example of using N4BiasFieldCorrection in command line at #342 in this page.
Please try this command in terminal to see if you can get good result.

If not, I do not have too much to help you. Sorry for that.   
You may search or put up an issue in ANTs or nipype.

Actually, lots of people had same trouble as yours, in which you could get some lights.
https://github.com/ANTsX/ANTs/issues/550
https://github.com/xf4j/brats17/issues/5
https://github.com/naldeborgh7575/brain_segmentation/issues/4
https://github.com/ANTsX/ANTs/issues/757

Good luck!

**Comment by wky1998** [comment]
Thanks.
I have solved the problem and successfully run bias_correction.py, but the output image is almost the same as the original image. Can some parameters in the program be changed to solve this problem?

**Comment by ZahidTufail** [comment]
> Thanks.
> I have solved the problem and successfully run bias_correction.py, but the output image is almost the same as the original image. Can some parameters in the program be changed to solve this problem?

How did you resolve this issue? Please share it here, Thanks

**Comment by ninjakx** [comment]
I am having the same problem I did add bin location to my path but still getting this error. @wky1998  Can you tell how did you solve it?

**Comment by HarshRangwala** [comment]
@wky1998  Hey there. Can you tell us how did you solve this? I am working on google colab.

**Comment by Habibo046** [comment]
@wky1998 
https://www.suyogjadhav.com/misc/2019/03/28/Using-ANTs-package-on-Google-Colaboratory/
