### ISSUE TITLE
scripts shouldn't have code that will run if imported

### ISSUE THREAD

**Issue by m-lyon** [quqixun/BrainPrep#3]
In general scripts shouldn't run functions when imported, which is what would happen with the scripts located in `src/`.

To only run code when being called as a script (and not from the `import` function) use:
```python
if __name__ == '__main__':
    # run functions here
```

This will prevent code being run if the user wishes to import the functions defined within the modules.

**Comment by quqixun** [comment]
You are right. 
This is not a package, but some demostrations of how to process MR images using open source tools.
You can establish your own scripts by picking up functions as you need. It's not difficult at all.
