### ISSUE TITLE
Qustions about application in general brain preprocessing 

### ISSUE THREAD

**Issue by Zjx01** [quqixun/BrainPrep#5]
Hi, I want to apply the pipeline to process nomral mri with 1 nii file for each subject. But I currently has no access to test dataset used in the profile, I am not clear about the reorganize and registration part, wether they work the same or just to skip the steps. A little bit explaination about relationship between NC1/2 and AD1/2 can help a lot, like whether they are from the same subject at diffrent stage and whether they are different modalities. Thanks!

**Comment by quqixun** [comment]
1. I am not clear about the reorganize and registration part, wether they work the same or just to skip the steps.

**Comment by quqixun** [comment]
1. I am not clear about the reorganize and registration part, wether they work the same or just to skip the steps.
If you have your own dataset, you can skip reorganize part.
If you do not have to match brain mri nii to a template mentioned [here](https://github.com/quqixun/BrainPrep/tree/master/data#template), you can skip registration part.

2. relationship between NC1/2 and AD1/2.
Honestly, I can not remember well about the details.
ADNI1 and ADNI2 have different subjects without stage annotation.
It is better to get access to ADNI dataset to get details.
