### ISSUE TITLE
N4BiasFieldCorrection issues 

### ISSUE THREAD

**Issue by Yueup** [quqixun/BrainPrep#6]
I encountered the following problem when running bias_correction.py 
**OSError: No command "N4BiasFieldCorrection" found on host ubuntu. Please check that the corresponding package is installed.**

But I have successfully installed ANTs, and when I try to run *which antsRegistration** in the terminal, it returns the Ant installation directory **/opt/ANTs/bin//antsRegistration** 

So how to solve the problem? Looking forward to your reply，thx!

**Comment by quqixun** [comment]
I am not familiar with the recent ants.
You may check the latest reply in this issue: https://github.com/ANTsX/ANTs/issues/876 .

**Comment by Yueup** [comment]
> I am not familiar with the recent ants.
> You may check the latest reply in this issue: [ANTsX/ANTs#876](https://github.com/ANTsX/ANTs/issues/876) .

ok ， appreciate it
