### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by CherishLii** [quqixun/BrainPrep#7]
hi there are some code cant use

**Comment by quqixun** [comment]
The code calls command line from FSL and ANTs.
You can forget the code in this repo, and read doc of latest FSL and ANTs to find out how to run your task.

**Comment by CherishLii** [comment]
thx
andi hava another question
First register, then peel off the skull. Is the resulting brain set unregistered?
I tried to register, after peeling off the skull, and then use mni_brain to register, so I can see that there is indeed a change

But when I continue to implement your bias correction, the enhance effect is not good? how to deal with this please

**Comment by CherishLii** [comment]
maybe the second register need to modify, but i dont know hot t
o modify the command
can u help me to modify the command for brain ?
def registration(src_path, dst_path, ref_path):
    command = ["flirt", "-in", src_path, "-ref", ref_path, "-out", dst_path,
               "-bins", "256", "-cost", "corratio", "-searchrx", "0", "0",
               "-searchry", "0", "0", "-searchrz", "0", "0", "-dof", "12", 
               "-interp", "spline"]
    subprocess.call(command, stdout=open(os.devnull, "r"),
                    stderr=subprocess.STDOUT)
    return

**Comment by quqixun** [comment]
Sorry, I cannot help you.
